### ISSUE TITLE
SHF_MAKE_HASH

### ISSUE THREAD

**Issue by pakipaki2000** [simonhf/sharedhashfile#11]
Hi,

Can you give me slighty more infos about : SHF_MAKE_HASH
I can insert a value and then getting the Uuid and retrieve it, but how do i use the SHF_MAKE_HASH?

I mean, can I retrieve DIRECTLY a value from a Key without having to compute the hash?
Thanks so much again

Also, how do I directly retrieve a value from a uuid I have?

**Comment by pakipaki2000** [comment]
And slighty more infos on this one:

 ok(0         == memcmp               (shf_val, "val" , 3), "c:     existing    get key: shf_val   

How do I retrieve a value from a uuid/key? In your example, it's only if you already know the value.

**Comment by simonhf** [comment]
Normally SHF_MAKE_HASH() must be used before any put or get operation involving a key (not a UID). It calculates the hash of the key which is automatically used by the next key operation, e.g. put or get.

"can I retrieve DIRECTLY a value from a Key without having to compute the hash" Kind of, using the UID. Or by discovering the direct address of the associated value... but this can easily cause issues unless you are an advanced developer and know what's going on. Why? Because the address can change under certain circumstances likely causing a seg fault unless you are sure that the memory address is not going to change.

If this is still confusing then please post very simple example code and I'll comment on it for you :-)

**Comment by pakipaki2000** [comment]
Thanks! That answer was enough, you are always very helpful, very much appreciated

**Comment by pakipaki2000** [comment]
It's faster to retrieve directly with the UID right? As it doesn't have to do the hash again?

**Comment by simonhf** [comment]
"It's faster to retrieve directly with the UID right? As it doesn't have to do the hash again?" Yes, that's correct. For smaller keys the performance difference is minimal. However, larger keys can make a bigger difference. HTH.

**Comment by pakipaki2000** [comment]
Thanks!
Last question, to update a value, is it possible to do it without checking if it exists?
As In, i'm not 100% sure I already inserted this key before, but i'll do a 

shf_put_key_val()
regardless, will it override the previous value or do i have to read the DB then Update?

**Comment by simonhf** [comment]
Yep, currently update will fail if the key,value or uid,value does not already exist. Plus even if the key,value or uid/value exists, update will only work if the values are exactly the same size.

But I might consider adding the functionality in future so that update will automatically create the key,value if it doesn't already exist. This should be relatively easy because both put and update use the more expensive writer lock.

BTW what type of application are you developing with SHF?

**Comment by pakipaki2000** [comment]
Actually it's just for testing for now, I had an idea that require 5 millions concurrent writing.

If i add twice a key (the same) with 2 different values, what happen inside the system?

**Comment by simonhf** [comment]
> If i add twice a key (the same) with 2 different values, what happen inside the system?

Probably not what you expect or want to happen. The code currently creates two keys with the same name which will likely result in confusion. I think I'll change this functionality in future so that the same key put again will result in an error return code rather than a second key being created.

> Did you made a function to list all the keys that are in the db?

Not yet in the code on github. I do have some experimental code which does something like that. It's trivial to come up with an API to list a few keys, but when there are 100s of millions of keys then things start to get tricky. Listing all the keys in one shot will take too long. And having some sort of cursor starts to get tricky. What's the use case that you have in mind?

**Comment by pakipaki2000** [comment]
I have to store a list of hashes and retrieve them all every 100ms (millions of them)

**Comment by simonhf** [comment]
> store a list of hashes and retrieve them all every 100ms (millions of them)

Do you mean "create key,values and iterative through them all every 100 ms"?

There is no way to do this with the current API. I have some experimental code to enhance shf.monitor so that a separate process background saves key,values in blocks of up to 8,192 key,values to disk or elsewhere on the RAM disk. Initial experiments have shown that doing such a background save does not affect performance much. Once saved then a separate process or processes could iterative through the key,value pairs and do whatever processing you like? Do you think this would be useful for you too?
