### ISSUE TITLE
Updating values

### ISSUE THREAD

**Issue by HandleMaser** [simonhf/sharedhashfile#13]
Morning!

How do you actually update values of a specific key, after I use SHF_MAKE_HASH.
How do I replace my value "HELLO" to "GOODB".

I've noticed in your samples "shf_upd_key_val", but I don't see any parameters to it outside the SHF set.
Have a great day Simon.

**Comment by simonhf** [comment]
Hello @HandleMaser and thanks for the good question!

'How do I replace my value "HELLO" to "GOODB"?'

To create a key with value "HELLO": First use SHF_MAKE_HASH() to make the hash for the desired key. Then use shf_put_key_val() to set the value for the key to "HELLO". 

To update a key to the next value "GOODB": Call shf_upd_callback_copy() with "GOODB". This remembers the string for the default update callback function. Next call shf_upd_key_val() which uses the same key hash (if you haven't called SHF_MAKE_HASH() again) to locate the key,value to update. Once located the default update callback function is called inside the write lock, which causes the update to appear as atomic for other SHF processes accessing the database. The default callback function updates the value with an exact sized new value... the value remembered after the shf_upd_callback_copy() call. The value will now have changed to "GOODB".

An example of updating a value can be found here [1] in the tests, which updates the test value "val" to "up1".

The default update callback can also be set to an arbitrary function that you the caller provides. An example of setting and using an arbitrary function can be found here [2] in the tests. After using shf_upd_callback_set() to set the new callback function, then when shf_upd_key_val() is called again, the newly set callback function gets called. In this case, it's upd_callback_test() [3] which swaps the first and last character of the value as an example; value 'up2' gets updated to value '2pu'.

Being able to set and use your own callback function to atomically update a value is powerful but also 'risky'. Ideally you want to do as little as possible in that callback function in order to keep performance high. While your callback function is running it is blocking all other read and write operations to that database shard in memory. Also, you should *not* do other key,value operations while you're in the callback function, otherwise the write lock for the hash table shard could go into an infinite loop. Also, you should also *not* do general operations that take a longer, or a variably longer period of time, such as calling system functions, etc.

'in your samples shf_upd_key_val(), but I don't see any parameters to it' The reason I gave it no parameters is because the callback function can be changed with shf_upd_callback_set() and maybe the replacement callback function requires no or different parameters. Sorry about this confusion, but the good news is that you get ultimate power to update the value however you want. For example, the value might be a chronological array of items, and your custom callback to update the array might push or pop items or whatever update logic you dream up. This would be impossible to update atomically if only an atomic string copy was available.

[1] https://github.com/simonhf/sharedhashfile/blob/6464d96b72be6e5422ea7ba50d03311dbfea9145/src/test.9.shf.c#L88
[2] https://github.com/simonhf/sharedhashfile/blob/6464d96b72be6e5422ea7ba50d03311dbfea9145/src/test.9.shf.c#L98
[3] https://github.com/simonhf/sharedhashfile/blob/6464d96b72be6e5422ea7ba50d03311dbfea9145/src/test.9.shf.c#L34

**Comment by pakipaki2000** [comment]
Wow, i'm really impressed with the degree of details of your explanations!
My issue is solved, thank you so much, you made my day :)

**Comment by HandleMaser** [comment]
Perfect, I'll close this issue, thank you;

**Comment by pakipaki2000** [comment]
Simon, when you do a shf_upd_callback_copy, it should immediately update it right?
There is no need to pass by the callback function? It's only if you want to actually have a callback right?

**Comment by pakipaki2000** [comment]
Would be amazing if there is a function to only do update to INSERT/UPDATE (in if it doesn't exist, it will insert), it would be so practical than having to check all the time.

performances are really impressive in my program.

**Comment by simonhf** [comment]
@pakipaki2000 Yep... it's on my todo list :-)
