### ISSUE TITLE
Iterator

### ISSUE THREAD

**Issue by NN-Binary** [simonhf/sharedhashfile#16]
Hello Simon!

Do you happen to have an example of an Iterator? Reading the whole DB in an lexico order?
I'm considering switching from Lmdb but I can't without this feature.

Thank you

**Comment by HandleMaser** [comment]
PS: In what order are the keys inserted?

**Comment by simonhf** [comment]
> Do you happen to have an example of an Iterator?

@HandleMaser There is currently no iterator implemented, but maybe this [1] answer is helpful in the meantime?

FYI I have plans for a new feature including a kind of iterator. The new feature will save the key,value pairs to disk using background processes which -- during initial tests -- appear to only very slightly affect performance of key,value access in RAM. This background save feature involves iterating through in batches of up to 8k key,value pairs.

> In what order are the keys inserted?

The keys are inserted in an order which is determined from the hash of the key.

If you wanted to iterate through the keys in some sort of sorted order -- e.g. chronological or ascending / descending key, etc -- then that'd be an extra feature to implement, and would likely have an impact on performance and/or size due to the overhead of managing the sorted order.

> switching from Lmdb but I can't without this feature

What is the feature / what type of sorting do you need?

AFAIK LMDB in built on top of a 'b-tree' [2], and trees are generally much handier for retrieving keys in sorted order, although they can also be slower depending upon size etc. Whereas hash tables can be faster but are also not known for helping to dish up data in sorted order.

One thing that you could also consider is running a hash table like SharedHashFile along side / in parallel to a tree-based DB like LMDB. Why? Although inserting new keys would remain slow (because LMDB is much slower, and the key would have to be inserted into both DBs), randomly reading keys would end up much faster because only SharedHashFile would be needed for the read. You could then use LMDB to read the keys in order even though functionality is not currently available with SharedHashFile. Regarding the data size then the keys would end up duplicated in both DBs, however, you could use the UID feature of SharedHashFile to de-duplicate the values. How? Insert the key,values into SharedHashFile first, and then insert the key,UID into LMDB.

[1] https://github.com/simonhf/sharedhashfile/issues/14#issuecomment-471777288
[2] https://stackoverflow.com/questions/35279756/what-is-special-about-internal-design-of-lmdb

**Comment by pakipaki2000** [comment]
Really Interested too for an iterator :) That's the main lacking function from SHF I believe
