### ISSUE TITLE
Donation for an iterator

### ISSUE THREAD

**Issue by pakipaki2000** [simonhf/sharedhashfile#17]
Hi Simon, how are you?

Are you willing to build a solid & fast Iterator if ever I'll send you a good donation? :)
My company is asking me but I'm not sure I would have the talent to do it myself.

Thanks!

**Comment by simonhf** [comment]
Hi @pakipaki2000,

Thanks for the offer and the question.

We have discussed the complexities of iterating in a previous thread and also shown that there are multiple ways to implement iterator functionality. Do you have an API for an iterator in mind? Can you describe what you'd like it to look like and how you'd like it to work? And can you describe your particular use case? E.g. how are keys added, manipulated, and deleted? How big are the keys and values? At which point do you do the iteration? How would iteration be used in your data usage scenario? Will you be iterating while still manipulating keys and values? What happens if a key gets added during the current iteration, but maybe gets missed because that part of the keys has already been iterated over? Is it okay to just wait until the next iteration? Do you have any particular performance requirements for the iteration, or must it just be 'as fast as possible'? Is it okay for the iteration to happen by a single thread in a single process? Or do you need multiple processes to iterate over all keys concurrently for ultimate performance?

Hope these questions help! If you want to discuss offline then my email is: simonhf@gmail.com

**Comment by pakipaki2000** [comment]
Keys are mostly sha256/sha512 keys (u8;32). 
I need one process only to iterate over all the keys inserted by multiple processes, however, I doubt those processes would still be writing at the time it's iterating.

So basically, insert insert insert... (multi-process) then a main process read it all.
Performance is critical, which is why i've talked about the "donation" so It might motivate you more :D
You've been so nice but we all have priorities and I don't want to abuse your time.

Keys are added randomly by many processes (up to 30), millions of them.
If possible, it would be indexed by lexico-order but it isn't mandatory, if it reduce performances too much then I'd rather not.

Thank you so much! :)

**Comment by simonhf** [comment]
Thanks @pakipaki2000 for fleshing out your use case.

> then a main process read it all

What happens after your program has iterated over all the keys? Do you start again with insert insert insert on a fresh and empty database, or do you continue to work on the same database until the next iteration phase? Or will the iteration itself manipulate the keys somehow, e.g. deleting or updating?

> If possible, it would be indexed by lexico-order

I cannot currently think of a way to do that which will not reduce performance significantly :-(

However, if the SHA256 is *both* the key and hash then it may be possible to arrange things so that the SHA256 keys are read in order... this would need further investigation. This is because SHF stores the keys in memory in the order of the key hashes.

Here are my thoughts so far:

Regarding general performance: The fastest way to iterate through the keys would be to make available an entire block of keys as a section of memory. That way the caller does not need to call a function for each individual key, and can just use some e.g. simple macros to navigate the memory. Such a block of memory would contain up to 8,192 keys. New SHF functions would iterate through all the blocks of memory containing sets of keys. So, e.g., 100 million keys might be stored in about 100M / 8,192 = 12,207 blocks of memory. This would be much faster than regular hash table operation because the RAM is being read consecutively and the CPU will auto read ahead which will work very efficiently. Whereas when reading a random key then the read ahead mechanism cannot be used and there is a performance penalty for fetching cache lines due to random access.

Regarding operation: If the database is effectively made read-only during the iteration phase, then performance can be increased again by not copying the keys and values iterated over, and simply giving a pointer to the caller which can iterate over the keys and value in-place in RAM.

Regarding general usage: I'm wondering how useful this feature would be for other SHF users. Or would it be only useful for your use case? Would other users want to iterate over the keys while SHF remains in read-write mode? Maybe it would be possible to implement both and let the caller decide?

If iterating in read-only mode then the address of a block of up to 8,192 keys in-place in RAM would be returned for each iteration.

And if iterating in read-write mode then the address of the copied block of up to 8,192 keys in RAM would be returned. This means as soon as the block of up to 8,192 keys is copied in RAM then other processes can continue to obtain the write lock on any of those copied keys while the iterating process iterates over individual copied keys in the copied block.

What do you think?

**Comment by pakipaki2000** [comment]
> Thanks @pakipaki2000 for fleshing out your use case.
> 
> > then a main process read it all
> 
> What happens after your program has iterated over all the keys? Do you start again with insert insert insert on a fresh and empty database, or do you continue to work on the same database until the next iteration phase? Or will the iteration itself manipulate the keys somehow, e.g. deleting or updating?
> 

Database is never emptied (in my case) or rarely, always working on the same DB, the iterator will not manipulate keys, only read them and do something "outside"

> > If possible, it would be indexed by lexico-order
> 
> I cannot currently think of a way to do that which will not reduce performance significantly :-(
> 
> However, if the SHA256 is _both_ the key and hash then it may be possible to arrange things so that the SHA256 keys are read in order... this would need further investigation. This is because SHF stores the keys in memory in the order of the key hashes.

That would be amazing, not sure if it's actually posssible, but this isn't a major issue if it's not.

> 
> Here are my thoughts so far:
> 
> Regarding general performance: The fastest way to iterate through the keys would be to make available an entire block of keys as a section of memory. That way the caller does not need to call a function for each individual key, and can just use some e.g. simple macros to navigate the memory. Such a block of memory would contain up to 8,192 keys. New SHF functions would iterate through all the blocks of memory containing sets of keys. So, e.g., 100 million keys might be stored in about 100M / 8,192 = 12,207 blocks of memory. This would be much faster than regular hash table operation because the RAM is being read consecutively and the CPU will auto read ahead which will work very efficiently. Whereas when reading a random key then the read ahead mechanism cannot be used and there is a performance penalty for fetching cache lines due to random access.
> 
> Regarding operation: If the database is effectively made read-only during the iteration phase, then performance can be increased again by not copying the keys and values iterated over, and simply giving a pointer to the caller which can iterate over the keys and value in-place in RAM.
> 
> Regarding general usage: I'm wondering how useful this feature would be for other SHF users. Or would it be only useful for your use case? Would other users want to iterate over the keys while SHF remains in read-write mode? Maybe it would be possible to implement both and let the caller decide?
> 

Not sure about that... but what i'm sure is probably a lot of people would use your DB if there was a basic Iterator.

> If iterating in read-only mode then the address of a block of up to 8,192 keys in-place in RAM would be returned for each iteration.
> 
> And if iterating in read-write mode then the address of the copied block of up to 8,192 keys in RAM would be returned. This means as soon as the block of up to 8,192 keys is copied in RAM then other processes can continue to obtain the write lock on any of those copied keys while the iterating process iterates over individual copied keys in the copied block.
> 
> What do you think?

That looks really fine.

Thanks again :)

**Comment by pakipaki2000** [comment]
Let us know Simon :)

**Comment by simonhf** [comment]
Hi @pakipaki2000, Things are busy at the moment. I would likely implement something similar or the same as the functionality you desire later in the year, if you can wait. If you need it sooner, then please email me at simon@linux.com and we can talk about your timeline.

**Comment by simonhf** [comment]
@pakipaki2000 never responded so closing the ticket.
