### ISSUE TITLE
how to change the value

### ISSUE THREAD

**Issue by kulegege** [simonhf/sharedhashfile#7]
I should use "SHF_MAKE_HASH() "and "shf_put_key_val()" when  need to add a key-value pair.   but how to change a value ? If I use "shf_get_key_val_addr()" then change the value, it seems unsafe :(

**Comment by kulegege** [comment]
oh,I see, when I use shf_make_hash() just finding the position of the value, the key is not stored in the hash list, so how to make sure shf_make_hash() find the unique node？and also how to change one value, only  del then add?

**Comment by simonhf** [comment]
"how to change a value ?" Recently I have been thinking about adding extra API calls for manipulating existing keys and values atomically. Stay tuned or feel free to make suggestions here :-)

Using the current API -- as of today -- there are a couple of ways but they all have pros and cons:

If multiple writer processes: Each writer should delete and re-put the key. Unfortunately, this also means that a reader might try to access between the two atomic accesses. And two writer processes might be in a race condition to write a new key,value.

Deleting keys like this can cause memory 'churn' because it's relatively expensive to clean up all the memory holes left over from deleted keys. However, a feature recently added allows you to create a DB using fixed key and value lengths. In this mode then deleted keys automatically get re-used without the more expensive clean up and avoiding the dreaded memory 'churn'.

The performance test tests only writing, mixed reading and writing, and only reading. With the mixed reading and (default 2%) writing then the percentage of writing can be specified and the DB can be optionally run in the fixed key and value length mode. For example, if you specify 50% reading and writing then performance gets worse due to the memory 'churn', but the same test with fixed key, value sizes is still super fast :-)

Writing (putting and deleting) keys is generally slower because about 1/256th of the keys get locked exclusively during the operations. Whereas, reading (getting) keys is generally faster because 1/256th of the keys get locked for reading but multiple readers can read at the same time. However, unlike other locking systems the locking is 'fair' which means if you have an enormous amount of readers and only one writer, the writer is guaranteed to grab the lock in order of lock access, whereas non-fair locking systems the readers can be so greedy that the writer can have a tough time grabbing the lock.

Also, please keep in mind that the locks are 'spin locks' which means that while waiting for the locks the thread literally spins -- burning CPU -- constantly examining the lock in memory. Normally spin locks are reserved for things like kernel code. Why? Because user land code can context switch while waiting for the spin lock, or while the spin lock is grabbed, thus causing all processes waiting for the spin lock to wait much longer until a context switch back to the process which eventually gives up its lock. So to get the best performance you need to consider virtually eliminating context switching in your user land processes which concurrently access the DB. This can be done in user land by having less processes active than there are CPUs, i.e. there are then no active processes to context switch to :-) If you really must have lots of processes and/or threads then you can lock them to particular CPU cores, which keeping other CPU cores exclusive for your readers and writers.

If single writer process and multiple reader processes with shorter atomic values: shf_get_key_val_addr() can be used to grab the address of the value in memory and *atomically* replace it with another value of the same size.

If single writer process and multiple reader processes with longer values: shf_get_key_val_addr() can be used to grab the address of the value in memory and replace it with another value of the same size. However, the value would need to have some kind of CRC (or two atomic values incremented before and after the string copy) appended because readers could read during the writing. This would mean an extra overhead in the reader to check the CRC (or atomic values) after reading and possibly re-read the string if necessary.

"it seems unsafe" Reading does not change the memory layout of key,values, only writing (putting and deleting) does. So if there is a single writer then it is in control of when key,value addresses may change.

Hope this helps!

**Comment by simonhf** [comment]
"how to just del only one key and its value" Have a look at the usage of  shf_del_uid_val() and shf_del_key_val() in the test programs.

**Comment by simonhf** [comment]
"I use shf_make_hash() just finding the position of the value" Kind of. It creates the hash for the key. Internally the hash is used to position the key in the hash table. Hashing a key is relatively expensive and there is a separate API for it so that callers can 'save' key hashing operations. For example, let's say you have a key called 'foo' and you want to delete the old key called 'foo' and then immediately put a new key called 'foo'. Most hash tables would build in the hashing part into the delete and put API calls, thus the key 'foo' ends up getting hashed unnecessarily twice; once for each operation. However, if the key is hashed once before calling delete and put then a saving can be made.

"how to make sure shf_make_hash() find the unique node" shf_make_hash() is not that useful for the caller in terms of functionality, and it's spun out of the key access API for achieving better performance under certain circumstances, as described above. But you want to "find the unique node". If you mean "find the unique key" then this can be done using code like " uid =  shf_put_key_val()". Let's say you put the key 'foo'. shf_put_key_val() returns a UID (AKA unique identifier). In the future you can then delete key 'foo' either using the returned UID via shf_del_uid_val() (which doesn't require the key string 'foo' for the deletion to succeed), or via shf_del_key_val() (which doesn't require the key UID for the deletion to succeed). Both delete operation delete the same key,value.

UIDs are also useful if you want to reference keys from other keys. Let's say you have a longer key called 'the quick brown fox jumps over the lazy dog'. If you want to reference that key from one or more values in other keys, it's much more memory efficient to use the short UID for reference than to include a copy of the longer key string.

**Comment by simonhf** [comment]
@kulegege Update: I just added shf_upd_key_val() & shf_upd_uid_val() which allows the caller code to update values in-place however they want to via a callback which defaults to a function which copies over the old value. Current limitation is that the old value and new value length must match. Both functions use the fair write lock described above. Example usage can be found in the test files.

**Comment by simonhf** [comment]
@kulegege Update: I just added shf_add_key_val() which is a reference counting mechanism for unique keys.

Example use case: Let's say you want to map IPs to user agent strings. User agent strings are typically longer. Multiple IPs might use the same user agent string. If the IP is the key and the user agent string is the value, then longer user agent strings will be unnecessarily duplicated if many IPs use the same user agent string. shf_add_key_val() is a way around this duplication. By storing the user agent string as a reference counted key via shf_add_key_val() then the IP,UID key,value pair can be stored instead of IP,user-agent-string where the UID is the UID from the shf_add_key_val() operation.
