### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by pakipaki2000** [simonhf/sharedhashfile#8]
Hi!

Thanks for this awesome lib.
I can't find the documentation for your lib? GET/PUT...?

Thanks Simon

**Comment by HandleMaser** [comment]
Same here, we can't use it without proper doc

**Comment by simonhf** [comment]
Hi @pakipaki2000 and @HandleMaser !

Thanks for asking the question about documentation.

The bad news:

1. There is no documentation.

2. You'll likely need to be a wiz at C/C++ to safely and optimally make use of this library due to the more difficult nature of shared memory and associated technologies in general.

The good news:

1. The library is *tiny* compared to other open source key,value stores such as Redis or Aerospike which are each +/- 100k LOC (lines of code). Java key,values stores like Cassandra or geode AKA GemFire are even bigger at 300k and 950k LOC respectively. SharedHashFile is only +/- 2k LOC. And the code is mostly in one file. You can literally page down a few times and you've seen it all :-)

2. Unlike many other open source projects, there are quite a few tests which exercise the API and therefore illustrate (hopefully) working examples of API usage.

3. There is a little documentation in the header file [1] about the inner workings :-)

4. If you ask any questions here then I will do my best to answer them, especially if you include example code.

HTH,
Simon

[1] https://github.com/simonhf/sharedhashfile/blob/master/src/shf.h#L25

**Comment by pakipaki2000** [comment]
Hi Simon!

Thanks for answering.
I'll provide you examples of code in case I run into troubles using.

PS: You should seriously consider marketing more (+ make a doc :D) your library because it might become widely used by ton of projects.

**Comment by simonhf** [comment]
Hi @pakipaki2000 !

Thanks for you comments.

"[SharedHashFile] might become widely used by ton of projects"

I'm not so sure because I think the library is very / too specialist. There's also tons of open-source and non-open-source hash table implementations available in all shapes and sizes, so lots to choose from, and IMO only a very few projects "need" the specialist features of SharedHashFile. And those few projects can easily exist *without* SharedHashFile... just perhaps slower and using more storage... which is perfectly acceptable for very many projects.

The seed of the idea for SharedHashFile formed after working for several years on such specialist projects at multiple companies. Generally the projects needed to deliver some kind of data, crazy fast via a network API. Typically the data would be huge (GBs...) and typical hash tables (even those in memory without a network API) would be considered too slow.

Such specialist projects might have used read only hash tables like CDB AKA Constant DB AKA Constant Database. Why? Technologies like CDB are much faster (and often smaller) than the fastest traditional read / write hash tables due to their read only functionality (which comes with many performance advantages for reading),  and can also be used in shared memory.

But read only hash tables are more difficult to update because generally only the entire DB can be updated. So let's say your CDB uses 16 GB of RAM... that means you need a box with 2x 16 = 32 GB of RAM to load in the new CDB while still serving from the old CDB... very annoying. You end up 'wasting' the other 16 GB of RAM most of the time... which is the cost of doing business. And perhaps more annoying is that the new 16 GB CDB might only contain a few updated keys but you're forced to regenerate the entire 16 GB CDB file... And this also puts a constraint on how often the CDB file can be updated... there must be a better why?! :-)

So SharedHashFile started life as an intellectual programming exercise to create a hash table with similar or better performance to a read-only hash table such as CDB, but where the hash table can also be updated incrementally in real time without using "double memory", and without having to regenerate the entire DB for each update. Luckily I had some time between jobs to design and implement this and SharedHashFile was born :-)

Interestingly one of the main features of SharedHashFile is not the performance or the ability to be used in shared memory, but the "Stable Key Hint" feature, which wasn't planned but I just stumbled across it during implementation. I don't know of any other hash table which has a similar feature. If you know, please tell me! And therein lies the problem: Most project developers are not aware of such a feature in other software, and therefore how can they get excited about a feature that they've never heard of? But again, it's possible to develop a project without that feature... it just ends up using more data and/or slower. Usually no big deal.

Another thing that SharedHashFile does really well is accessing larger batches of keys. This is something that other hash tables typically don't do that well. However, there is a hidden caveat. Let's say you want to access a batch of 50 keys. Typically to get better performance with other hash tables, you might shard the DB so that the shards can work in parallel. While this sounds good in theory, it means that worst case you'll have to dispatch up to 50 network requests to up to 50 shards. If only you could dispatch 1 network request to 1 box which services the entire batch... you'd then end up doing up to 50x less network activity. And often network activity is much slower than hash table activity; you need to be really on top of things technically if you want your NIC to be doing 10M packets per second... but it's not difficult to get SharedHashFile to read 10M keys per second. This is the type of thing where SharedHashFile can be very useful. But again, it's a very specialized use case and also not a silver bullet solution for all similar "unsharding" use cases.

I think there are only two main reasons to use SharedHashFile over alternative hash tables: (1) Your project *must* for some reason achieve ultimate performance not achievable with alternatives... and this is specialized and unlikely, or (2) Your project is so vast in magnitude that due to the economies of scale you can save 10x or 100x network and/or boxes in operating costs by using SharedHashFile... and again this is specialized and unlikely.

Anyway, if you have a potential use-case for SharedHashFile and can describe the perceived pros and cons for other hash table solutions here, then I'll happily weigh in on the argument, and there are likely to be many good reasons to use an alternative hash table :-)
